SELECT
    E.CODIGO_PROVEEDOR,
    E.PROVEEDOR,
    E.TIPO_DOCTO_ID || '-' || E.TIPO_DOCTO TIPO_DOCTO,
    E.INGRESO_ORDEN,
    E.DOCUMENTO,
    E.FECHA,
    SUM(CASE WHEN E.DIAS BETWEEN -30 AND -1 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCIDO_30,
    SUM(CASE WHEN E.DIAS BETWEEN -60 AND -31 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCIDO_60,
    SUM(CASE WHEN E.DIAS BETWEEN -90 AND -61 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCIDO_90,
    SUM(CASE WHEN E.DIAS BETWEEN -120 AND -91 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCIDO_120,
    SUM(CASE WHEN E.DIAS < -120 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCIDO_MAS,
    SUM(CASE WHEN E.DIAS < 0 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCIDO_TOTAL,
    SUM(CASE WHEN E.DIAS BETWEEN 0 AND 30 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCER_30,
    SUM(CASE WHEN E.DIAS BETWEEN 31 AND 60 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCER_60,
    SUM(CASE WHEN E.DIAS BETWEEN 61 AND 90 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCER_90,
    SUM(CASE WHEN E.DIAS BETWEEN 91 AND 120 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCER_120,
    SUM(CASE WHEN E.DIAS > 120 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCER_MAS,
    SUM(CASE WHEN E.DIAS >= 0 THEN E.VALOR + E.PAGADO ELSE 0 END) VENCER_TOTAL,
    ROUND(SUM(E.VALOR) + SUM(E.PAGADO), 2) SALDO,
    SUM(E.DEBITOS) DEBITO_POR_APLICAR,
    ROUND(SUM(E.VALOR) + SUM(E.PAGADO) + SUM(E.DEBITOS), 2) SALDO_APLICADO
FROM (
WITH CARGOS AS (
    SELECT * 
    FROM TABLE(CXPDB.DOCUMENTOS_CARGOS_ABONOS(:EMPRESA, :FECHA, :LOCAL_EXT, :TIPO_MONEDA, :TIPO_FECHA, :INCLUYE_TIPO_DOCTOS, :LISTA_TIPO_DOCTOS, :INCLUYE_PROVS, :LISTA_PROVS))
    WHERE
        TIPO_MOV = 'C'
), ABONOS AS (
    SELECT * 
    FROM TABLE(CXPDB.DOCUMENTOS_CARGOS_ABONOS(:EMPRESA, :FECHA, :LOCAL_EXT, :TIPO_MONEDA, :TIPO_FECHA, :INCLUYE_TIPO_DOCTOS, :LISTA_TIPO_DOCTOS, :INCLUYE_PROVS, :LISTA_PROVS))
    WHERE
        TIPO_MOV = 'A'
)
SELECT
    C.CODIGO_PROVEEDOR,
    C.PROVEEDOR,
    C.DOCUMENTO_ID,
    C.DOCUMENTO,
    C.FECHA,
    C.MONEDA_ID,
    C.INGRESO_ORDEN,
    C.TIPO_DOCTO_ID,
    C.TIPO_DOCTO,
    C.FECHA_PAGO,
    C.FECHA_PAGO - TO_DATE(:FECHA, 'DD/MM/YYYY') DIAS,
    C.CUOTA_ID,
    MAX(C.VALOR) VALOR,
    SUM(-NVL(A.VALOR, 0)) PAGADO,
    0 DEBITOS
FROM CARGOS C
LEFT JOIN ABONOS A ON A.CUOTA_ID = C.CUOTA_ID
GROUP BY C.CODIGO_PROVEEDOR, C.PROVEEDOR, C.DOCUMENTO_ID, C.DOCUMENTO, C.FECHA, C.MONEDA_ID, C.INGRESO_ORDEN, C.FECHA_PAGO, C.CUOTA_ID, C.TIPO_DOCTO_ID, C.TIPO_DOCTO
UNION ALL
SELECT
    A.CODIGO_PROVEEDOR,
    A.PROVEEDOR,
    A.DOCUMENTO_ID,
    A.DOCUMENTO,
    A.FECHA,
    A.MONEDA_ID,
    A.INGRESO_ORDEN,
    A.TIPO_DOCTO_ID,
    A.TIPO_DOCTO,
    NULL FECHA_PAGO,
    NULL DIAS,
    NULL CUOTA_ID,
    0 VALOR,
    0 PAGADO,
    SUM(-NVL(A.VALOR, 0)) DEBITOS
FROM ABONOS A
LEFT JOIN CARGOS C ON C.CUOTA_ID = A.CUOTA_ID
WHERE
    C.CUOTA_ID IS NULL AND A.CUOTA_ID IS NOT NULL
GROUP BY A.CODIGO_PROVEEDOR, A.PROVEEDOR, A.DOCUMENTO_ID, A.DOCUMENTO, A.FECHA, A.MONEDA_ID, A.INGRESO_ORDEN, A.TIPO_DOCTO_ID, A.TIPO_DOCTO
UNION ALL
SELECT
    D.CODIGO_PROVEEDOR,
    D.PROVEEDOR,
    D.DOCUMENTO_ID,
    D.DOCUMENTO,
    D.FECHA,
    D.MONEDA_ID,
    D.INGRESO_ORDEN,
    D.TIPO_DOCTO_ID,
    D.TIPO_DOCTO,
    NULL FECHA_PAGO,
    NULL DIAS,
    NULL CUOTA_ID,
    0 VALOR,
    0 PAGADO,
    SUM(-NVL(D.VALOR, 0)) DEBITOS
FROM ABONOS D
WHERE
    D.CUOTA_ID IS NULL
GROUP BY D.CODIGO_PROVEEDOR, D.PROVEEDOR, D.DOCUMENTO_ID, D.DOCUMENTO, D.FECHA, D.MONEDA_ID, D.INGRESO_ORDEN, D.TIPO_DOCTO_ID, D.TIPO_DOCTO
) E
GROUP BY E.CODIGO_PROVEEDOR, E.PROVEEDOR, E.TIPO_DOCTO_ID || '-' || E.TIPO_DOCTO, E.INGRESO_ORDEN, E.DOCUMENTO, E.FECHA
HAVING ROUND(SUM(VALOR) + SUM(PAGADO) + SUM(DEBITOS), 2) <> 0
ORDER BY E.CODIGO_PROVEEDOR;